import {
  IconBell,
  IconBellBolt,
  IconBellCancel,
  IconBellCheck,
  IconBellCode,
  IconBellCog,
  IconBellDollar,
  IconBellDown,
  IconBellExclamation,
  IconBellFilled,
  IconBellHeart,
  IconBellMinus,
  IconBellMinusFilled,
  IconBellOff,
  IconBellPause,
  IconBellPin,
  IconBellPlus,
  IconBellPlusFilled,
  IconBellQuestion,
  IconBellRinging,
  IconBellRinging2,
  IconBellRinging2Filled,
  IconBellRingingFilled,
  IconBellSchool,
  IconBellSearch,
  IconBellShare,
  IconBellStar,
  IconBellUp,
  IconBellX,
  IconBellXFilled,
  IconBellZ,
  IconBellZFilled,
} from '@tabler/icons-react';

import { createIcon } from '../create-icon';

export const BellIcon = createIcon(
  'BellIcon',
  {
    outline: (props) => <IconBell {...props} />,
    filled: (props) => <IconBellFilled {...props} />,
    ringing: (props) => <IconBellRinging {...props} />,
    ringing2: (props) => <IconBellRinging2 {...props} />,
    ringingFilled: (props) => <IconBellRingingFilled {...props} />,
    ringing2Filled: (props) => <IconBellRinging2Filled {...props} />,
    off: (props) => <IconBellOff {...props} />,
    bolt: (props) => <IconBellBolt {...props} />,
    cancel: (props) => <IconBellCancel {...props} />,
    check: (props) => <IconBellCheck {...props} />,
    code: (props) => <IconBellCode {...props} />,
    cog: (props) => <IconBellCog {...props} />,
    dollar: (props) => <IconBellDollar {...props} />,
    down: (props) => <IconBellDown {...props} />,
    exclamation: (props) => <IconBellExclamation {...props} />,
    heart: (props) => <IconBellHeart {...props} />,
    minus: (props) => <IconBellMinus {...props} />,
    minusFilled: (props) => <IconBellMinusFilled {...props} />,
    pause: (props) => <IconBellPause {...props} />,
    pin: (props) => <IconBellPin {...props} />,
    plus: (props) => <IconBellPlus {...props} />,
    plusFilled: (props) => <IconBellPlusFilled {...props} />,
    question: (props) => <IconBellQuestion {...props} />,
    school: (props) => <IconBellSchool {...props} />,
    search: (props) => <IconBellSearch {...props} />,
    share: (props) => <IconBellShare {...props} />,
    star: (props) => <IconBellStar {...props} />,
    up: (props) => <IconBellUp {...props} />,
    x: (props) => <IconBellX {...props} />,
    xFilled: (props) => <IconBellXFilled {...props} />,
    z: (props) => <IconBellZ {...props} />,
    zFilled: (props) => <IconBellZFilled {...props} />,
  },
  'outline',
);
