import {
  IconCalendar,
  IconCalendarBolt,
  IconCalendarCancel,
  IconCalendarCheck,
  IconCalendarClock,
  IconCalendarCode,
  IconCalendarCog,
  IconCalendarDollar,
  IconCalendarDot,
  IconCalendarDown,
  IconCalendarDue,
  IconCalendarEvent,
  IconCalendarEventFilled,
  IconCalendarExclamation,
  IconCalendarFilled,
  IconCalendarHeart,
  IconCalendarMinus,
  IconCalendarMonth,
  IconCalendarMonthFilled,
  IconCalendarOff,
  IconCalendarPause,
  IconCalendarPin,
  IconCalendarPlus,
  IconCalendarQuestion,
  IconCalendarRepeat,
  IconCalendarSad,
  IconCalendarSearch,
  IconCalendarShare,
  IconCalendarSmile,
  IconCalendarStar,
  IconCalendarStats,
  IconCalendarTime,
  IconCalendarUp,
  IconCalendarUser,
  IconCalendarWeek,
  IconCalendarWeekFilled,
  IconCalendarX,
} from '@tabler/icons-react';

import { createIcon } from '../create-icon';

export const CalendarIcon = createIcon(
  'CalendarIcon',
  {
    outline: (props) => <IconCalendar {...props} />,
    filled: (props) => <IconCalendarFilled {...props} />,
    off: (props) => <IconCalendarOff {...props} />,
    check: (props) => <IconCalendarCheck {...props} />,
    x: (props) => <IconCalendarX {...props} />,
    plus: (props) => <IconCalendarPlus {...props} />,
    minus: (props) => <IconCalendarMinus {...props} />,
    event: (props) => <IconCalendarEvent {...props} />,
    eventFilled: (props) => <IconCalendarEventFilled {...props} />,
    clock: (props) => <IconCalendarClock {...props} />,
    time: (props) => <IconCalendarTime {...props} />,
    week: (props) => <IconCalendarWeek {...props} />,
    weekFilled: (props) => <IconCalendarWeekFilled {...props} />,
    month: (props) => <IconCalendarMonth {...props} />,
    monthFilled: (props) => <IconCalendarMonthFilled {...props} />,
    dot: (props) => <IconCalendarDot {...props} />,
    due: (props) => <IconCalendarDue {...props} />,
    repeat: (props) => <IconCalendarRepeat {...props} />,
    stats: (props) => <IconCalendarStats {...props} />,
    user: (props) => <IconCalendarUser {...props} />,
    search: (props) => <IconCalendarSearch {...props} />,
    bolt: (props) => <IconCalendarBolt {...props} />,
    cancel: (props) => <IconCalendarCancel {...props} />,
    code: (props) => <IconCalendarCode {...props} />,
    cog: (props) => <IconCalendarCog {...props} />,
    dollar: (props) => <IconCalendarDollar {...props} />,
    down: (props) => <IconCalendarDown {...props} />,
    exclamation: (props) => <IconCalendarExclamation {...props} />,
    heart: (props) => <IconCalendarHeart {...props} />,
    pause: (props) => <IconCalendarPause {...props} />,
    pin: (props) => <IconCalendarPin {...props} />,
    question: (props) => <IconCalendarQuestion {...props} />,
    sad: (props) => <IconCalendarSad {...props} />,
    share: (props) => <IconCalendarShare {...props} />,
    smile: (props) => <IconCalendarSmile {...props} />,
    star: (props) => <IconCalendarStar {...props} />,
    up: (props) => <IconCalendarUp {...props} />,
  },
  'outline',
);
