import {
  IconEye,
  IconEyeBitcoin,
  IconEyeBolt,
  IconEyeCancel,
  IconEyeCheck,
  IconEyeClosed,
  IconEyeCode,
  IconEyeCog,
  IconEyeDiscount,
  IconEyeDollar,
  IconEyeDotted,
  IconEyeDown,
  IconEyeEdit,
  IconEyeExclamation,
  IconEyeFilled,
  IconEyeHeart,
  IconEyeMinus,
  IconEyeOff,
  IconEyePause,
  IconEyePin,
  IconEyePlus,
  IconEyeQuestion,
  IconEyeSearch,
  IconEyeShare,
  IconEyeSpark,
  IconEyeStar,
  IconEyeTable,
  IconEyeTableFilled,
  IconEyeUp,
  IconEyeX,
} from '@tabler/icons-react';

import { createIcon } from '../create-icon';

export const EyeIcon = createIcon(
  'EyeIcon',
  {
    outline: (props) => <IconEye {...props} />,
    filled: (props) => <IconEyeFilled {...props} />,
    off: (props) => <IconEyeOff {...props} />,
    closed: (props) => <IconEyeClosed {...props} />,
    dotted: (props) => <IconEyeDotted {...props} />,
    check: (props) => <IconEyeCheck {...props} />,
    x: (props) => <IconEyeX {...props} />,
    plus: (props) => <IconEyePlus {...props} />,
    minus: (props) => <IconEyeMinus {...props} />,
    edit: (props) => <IconEyeEdit {...props} />,
    search: (props) => <IconEyeSearch {...props} />,
    bolt: (props) => <IconEyeBolt {...props} />,
    cancel: (props) => <IconEyeCancel {...props} />,
    code: (props) => <IconEyeCode {...props} />,
    cog: (props) => <IconEyeCog {...props} />,
    bitcoin: (props) => <IconEyeBitcoin {...props} />,
    discount: (props) => <IconEyeDiscount {...props} />,
    dollar: (props) => <IconEyeDollar {...props} />,
    down: (props) => <IconEyeDown {...props} />,
    exclamation: (props) => <IconEyeExclamation {...props} />,
    heart: (props) => <IconEyeHeart {...props} />,
    pause: (props) => <IconEyePause {...props} />,
    pin: (props) => <IconEyePin {...props} />,
    question: (props) => <IconEyeQuestion {...props} />,
    share: (props) => <IconEyeShare {...props} />,
    spark: (props) => <IconEyeSpark {...props} />,
    star: (props) => <IconEyeStar {...props} />,
    table: (props) => <IconEyeTable {...props} />,
    tableFilled: (props) => <IconEyeTableFilled {...props} />,
    up: (props) => <IconEyeUp {...props} />,
  },
  'outline',
);
