import {
  IconFilter,
  IconFilter2,
  IconFilter2Bolt,
  IconFilter2Cancel,
  IconFilter2Check,
  IconFilter2Code,
  IconFilter2Cog,
  IconFilter2Discount,
  IconFilter2Dollar,
  IconFilter2Down,
  IconFilter2Edit,
  IconFilter2Exclamation,
  IconFilter2Minus,
  IconFilter2Pause,
  IconFilter2Pin,
  IconFilter2Plus,
  IconFilter2Question,
  IconFilter2Search,
  IconFilter2Share,
  IconFilter2Spark,
  IconFilter2Up,
  IconFilter2X,
  IconFilterBolt,
  IconFilterCancel,
  IconFilterCheck,
  IconFilterCode,
  IconFilterCog,
  IconFilterDiscount,
  IconFilterDollar,
  IconFilterDown,
  IconFilterEdit,
  IconFilterExclamation,
  IconFilterFilled,
  IconFilterHeart,
  IconFilterMinus,
  IconFilterOff,
  IconFilterPause,
  IconFilterPin,
  IconFilterPlus,
  IconFilterQuestion,
  IconFilterSearch,
  IconFilterShare,
  IconFilterSpark,
  IconFilterStar,
  IconFilterUp,
  IconFilterX,
} from '@tabler/icons-react';

import { createIcon } from '../create-icon';

export const FilterIcon = createIcon(
  'FilterIcon',
  {
    outline: (props) => <IconFilter {...props} />,
    filled: (props) => <IconFilterFilled {...props} />,
    off: (props) => <IconFilterOff {...props} />,
    check: (props) => <IconFilterCheck {...props} />,
    x: (props) => <IconFilterX {...props} />,
    plus: (props) => <IconFilterPlus {...props} />,
    minus: (props) => <IconFilterMinus {...props} />,
    bolt: (props) => <IconFilterBolt {...props} />,
    cancel: (props) => <IconFilterCancel {...props} />,
    code: (props) => <IconFilterCode {...props} />,
    cog: (props) => <IconFilterCog {...props} />,
    discount: (props) => <IconFilterDiscount {...props} />,
    dollar: (props) => <IconFilterDollar {...props} />,
    down: (props) => <IconFilterDown {...props} />,
    edit: (props) => <IconFilterEdit {...props} />,
    exclamation: (props) => <IconFilterExclamation {...props} />,
    heart: (props) => <IconFilterHeart {...props} />,
    pause: (props) => <IconFilterPause {...props} />,
    pin: (props) => <IconFilterPin {...props} />,
    question: (props) => <IconFilterQuestion {...props} />,
    search: (props) => <IconFilterSearch {...props} />,
    share: (props) => <IconFilterShare {...props} />,
    spark: (props) => <IconFilterSpark {...props} />,
    star: (props) => <IconFilterStar {...props} />,
    up: (props) => <IconFilterUp {...props} />,
    alt: (props) => <IconFilter2 {...props} />,
    altBolt: (props) => <IconFilter2Bolt {...props} />,
    altCancel: (props) => <IconFilter2Cancel {...props} />,
    altCheck: (props) => <IconFilter2Check {...props} />,
    altCode: (props) => <IconFilter2Code {...props} />,
    altCog: (props) => <IconFilter2Cog {...props} />,
    altDiscount: (props) => <IconFilter2Discount {...props} />,
    altDollar: (props) => <IconFilter2Dollar {...props} />,
    altDown: (props) => <IconFilter2Down {...props} />,
    altEdit: (props) => <IconFilter2Edit {...props} />,
    altExclamation: (props) => <IconFilter2Exclamation {...props} />,
    altMinus: (props) => <IconFilter2Minus {...props} />,
    altPause: (props) => <IconFilter2Pause {...props} />,
    altPin: (props) => <IconFilter2Pin {...props} />,
    altPlus: (props) => <IconFilter2Plus {...props} />,
    altQuestion: (props) => <IconFilter2Question {...props} />,
    altSearch: (props) => <IconFilter2Search {...props} />,
    altShare: (props) => <IconFilter2Share {...props} />,
    altSpark: (props) => <IconFilter2Spark {...props} />,
    altUp: (props) => <IconFilter2Up {...props} />,
    altX: (props) => <IconFilter2X {...props} />,
  },
  'outline',
);
