import {
  IconHeart,
  IconHeartBitcoin,
  IconHeartBolt,
  IconHeartBroken,
  IconHeartBrokenFilled,
  IconHeartCancel,
  IconHeartCheck,
  IconHeartCode,
  IconHeartCog,
  IconHeartDiscount,
  IconHeartDollar,
  IconHeartDown,
  IconHeartExclamation,
  IconHeartFilled,
  IconHeartHandshake,
  IconHeartMinus,
  IconHeartOff,
  IconHeartPause,
  IconHeartPin,
  IconHeartPlus,
  IconHeartQuestion,
  IconHeartRateMonitor,
  IconHeartSearch,
  IconHeartShare,
  IconHeartSpark,
  IconHeartStar,
  IconHeartUp,
  IconHeartX,
} from '@tabler/icons-react';

import { createIcon } from '../create-icon';

export const HeartIcon = createIcon(
  'HeartIcon',
  {
    outline: (props) => <IconHeart {...props} />,
    filled: (props) => <IconHeartFilled {...props} />,
    broken: (props) => <IconHeartBroken {...props} />,
    brokenFilled: (props) => <IconHeartBrokenFilled {...props} />,
    off: (props) => <IconHeartOff {...props} />,
    bitcoin: (props) => <IconHeartBitcoin {...props} />,
    bolt: (props) => <IconHeartBolt {...props} />,
    cancel: (props) => <IconHeartCancel {...props} />,
    check: (props) => <IconHeartCheck {...props} />,
    code: (props) => <IconHeartCode {...props} />,
    cog: (props) => <IconHeartCog {...props} />,
    discount: (props) => <IconHeartDiscount {...props} />,
    dollar: (props) => <IconHeartDollar {...props} />,
    down: (props) => <IconHeartDown {...props} />,
    exclamation: (props) => <IconHeartExclamation {...props} />,
    handshake: (props) => <IconHeartHandshake {...props} />,
    minus: (props) => <IconHeartMinus {...props} />,
    pause: (props) => <IconHeartPause {...props} />,
    pin: (props) => <IconHeartPin {...props} />,
    plus: (props) => <IconHeartPlus {...props} />,
    question: (props) => <IconHeartQuestion {...props} />,
    rateMonitor: (props) => <IconHeartRateMonitor {...props} />,
    search: (props) => <IconHeartSearch {...props} />,
    share: (props) => <IconHeartShare {...props} />,
    spark: (props) => <IconHeartSpark {...props} />,
    star: (props) => <IconHeartStar {...props} />,
    up: (props) => <IconHeartUp {...props} />,
    x: (props) => <IconHeartX {...props} />,
  },
  'outline',
);
