import {
  IconLock,
  IconLockAccess,
  IconLockAccessOff,
  IconLockBitcoin,
  IconLockBolt,
  IconLockCancel,
  IconLockCheck,
  IconLockCode,
  IconLockCog,
  IconLockDollar,
  IconLockDown,
  IconLockExclamation,
  IconLockFilled,
  IconLockHeart,
  IconLockMinus,
  IconLockOff,
  IconLockOpen,
  IconLockOpen2,
  IconLockOpenOff,
  IconLockPassword,
  IconLockPause,
  IconLockPin,
  IconLockPlus,
  IconLockQuestion,
  IconLockSearch,
  IconLockShare,
  IconLockSquare,
  IconLockSquareRounded,
  IconLockSquareRoundedFilled,
  IconLockStar,
  IconLockUp,
  IconLockX,
} from '@tabler/icons-react';

import { createIcon } from '../create-icon';

export const LockIcon = createIcon(
  'LockIcon',
  {
    outline: (props) => <IconLock {...props} />,
    filled: (props) => <IconLockFilled {...props} />,
    off: (props) => <IconLockOff {...props} />,
    open: (props) => <IconLockOpen {...props} />,
    open2: (props) => <IconLockOpen2 {...props} />,
    openOff: (props) => <IconLockOpenOff {...props} />,
    access: (props) => <IconLockAccess {...props} />,
    accessOff: (props) => <IconLockAccessOff {...props} />,
    password: (props) => <IconLockPassword {...props} />,
    square: (props) => <IconLockSquare {...props} />,
    squareRounded: (props) => <IconLockSquareRounded {...props} />,
    squareRoundedFilled: (props) => <IconLockSquareRoundedFilled {...props} />,
    check: (props) => <IconLockCheck {...props} />,
    x: (props) => <IconLockX {...props} />,
    plus: (props) => <IconLockPlus {...props} />,
    minus: (props) => <IconLockMinus {...props} />,
    bolt: (props) => <IconLockBolt {...props} />,
    bitcoin: (props) => <IconLockBitcoin {...props} />,
    cancel: (props) => <IconLockCancel {...props} />,
    code: (props) => <IconLockCode {...props} />,
    cog: (props) => <IconLockCog {...props} />,
    dollar: (props) => <IconLockDollar {...props} />,
    down: (props) => <IconLockDown {...props} />,
    exclamation: (props) => <IconLockExclamation {...props} />,
    heart: (props) => <IconLockHeart {...props} />,
    pause: (props) => <IconLockPause {...props} />,
    pin: (props) => <IconLockPin {...props} />,
    question: (props) => <IconLockQuestion {...props} />,
    search: (props) => <IconLockSearch {...props} />,
    share: (props) => <IconLockShare {...props} />,
    star: (props) => <IconLockStar {...props} />,
    up: (props) => <IconLockUp {...props} />,
  },
  'outline',
);
