import {
  IconPhoto,
  IconPhotoAi,
  IconPhotoBitcoin,
  IconPhotoBolt,
  IconPhotoCancel,
  IconPhotoCheck,
  IconPhotoCircle,
  IconPhotoCircleMinus,
  IconPhotoCirclePlus,
  IconPhotoCode,
  IconPhotoCog,
  IconPhotoDollar,
  IconPhotoDown,
  IconPhotoEdit,
  IconPhotoExclamation,
  IconPhotoFilled,
  IconPhotoHeart,
  IconPhotoHexagon,
  IconPhotoMinus,
  IconPhotoOff,
  IconPhotoPause,
  IconPhotoPentagon,
  IconPhotoPin,
  IconPhotoPlus,
  IconPhotoQuestion,
  IconPhotoScan,
  IconPhotoSearch,
  IconPhotoSensor,
  IconPhotoSensor2,
  IconPhotoSensor3,
  IconPhotoShare,
  IconPhotoShield,
  IconPhotoSpark,
  IconPhotoSquareRounded,
  IconPhotoStar,
  IconPhotoUp,
  IconPhotoVideo,
  IconPhotoX,
} from '@tabler/icons-react';

import { createIcon } from '../create-icon';

export const PhotoIcon = createIcon(
  'PhotoIcon',
  {
    outline: (props) => <IconPhoto {...props} />,
    filled: (props) => <IconPhotoFilled {...props} />,
    off: (props) => <IconPhotoOff {...props} />,
    ai: (props) => <IconPhotoAi {...props} />,
    check: (props) => <IconPhotoCheck {...props} />,
    x: (props) => <IconPhotoX {...props} />,
    plus: (props) => <IconPhotoPlus {...props} />,
    minus: (props) => <IconPhotoMinus {...props} />,
    edit: (props) => <IconPhotoEdit {...props} />,
    scan: (props) => <IconPhotoScan {...props} />,
    search: (props) => <IconPhotoSearch {...props} />,
    circle: (props) => <IconPhotoCircle {...props} />,
    circlePlus: (props) => <IconPhotoCirclePlus {...props} />,
    circleMinus: (props) => <IconPhotoCircleMinus {...props} />,
    squareRounded: (props) => <IconPhotoSquareRounded {...props} />,
    hexagon: (props) => <IconPhotoHexagon {...props} />,
    pentagon: (props) => <IconPhotoPentagon {...props} />,
    sensor: (props) => <IconPhotoSensor {...props} />,
    sensor2: (props) => <IconPhotoSensor2 {...props} />,
    sensor3: (props) => <IconPhotoSensor3 {...props} />,
    video: (props) => <IconPhotoVideo {...props} />,
    bolt: (props) => <IconPhotoBolt {...props} />,
    bitcoin: (props) => <IconPhotoBitcoin {...props} />,
    cancel: (props) => <IconPhotoCancel {...props} />,
    code: (props) => <IconPhotoCode {...props} />,
    cog: (props) => <IconPhotoCog {...props} />,
    dollar: (props) => <IconPhotoDollar {...props} />,
    down: (props) => <IconPhotoDown {...props} />,
    exclamation: (props) => <IconPhotoExclamation {...props} />,
    heart: (props) => <IconPhotoHeart {...props} />,
    pause: (props) => <IconPhotoPause {...props} />,
    pin: (props) => <IconPhotoPin {...props} />,
    question: (props) => <IconPhotoQuestion {...props} />,
    share: (props) => <IconPhotoShare {...props} />,
    shield: (props) => <IconPhotoShield {...props} />,
    spark: (props) => <IconPhotoSpark {...props} />,
    star: (props) => <IconPhotoStar {...props} />,
    up: (props) => <IconPhotoUp {...props} />,
  },
  'outline',
);
