import {
  IconWorld,
  IconWorldBolt,
  IconWorldCancel,
  IconWorldCheck,
  IconWorldCode,
  IconWorldCog,
  IconWorldDollar,
  IconWorldDown,
  IconWorldDownload,
  IconWorldExclamation,
  IconWorldFilled,
  IconWorldHeart,
  IconWorldLatitude,
  IconWorldLongitude,
  IconWorldMap,
  IconWorldMinus,
  IconWorldOff,
  IconWorldPause,
  IconWorldPin,
  IconWorldPlus,
  IconWorldQuestion,
  IconWorldSearch,
  IconWorldShare,
  IconWorldStar,
  IconWorldUp,
  IconWorldUpload,
  IconWorldWww,
  IconWorldX,
} from '@tabler/icons-react';

import { createIcon } from '../create-icon';

export const WorldIcon = createIcon(
  'WorldIcon',
  {
    outline: (props) => <IconWorld {...props} />,
    filled: (props) => <IconWorldFilled {...props} />,
    off: (props) => <IconWorldOff {...props} />,
    www: (props) => <IconWorldWww {...props} />,
    map: (props) => <IconWorldMap {...props} />,
    latitude: (props) => <IconWorldLatitude {...props} />,
    longitude: (props) => <IconWorldLongitude {...props} />,
    check: (props) => <IconWorldCheck {...props} />,
    x: (props) => <IconWorldX {...props} />,
    plus: (props) => <IconWorldPlus {...props} />,
    minus: (props) => <IconWorldMinus {...props} />,
    download: (props) => <IconWorldDownload {...props} />,
    upload: (props) => <IconWorldUpload {...props} />,
    search: (props) => <IconWorldSearch {...props} />,
    bolt: (props) => <IconWorldBolt {...props} />,
    cancel: (props) => <IconWorldCancel {...props} />,
    code: (props) => <IconWorldCode {...props} />,
    cog: (props) => <IconWorldCog {...props} />,
    dollar: (props) => <IconWorldDollar {...props} />,
    down: (props) => <IconWorldDown {...props} />,
    exclamation: (props) => <IconWorldExclamation {...props} />,
    heart: (props) => <IconWorldHeart {...props} />,
    pause: (props) => <IconWorldPause {...props} />,
    pin: (props) => <IconWorldPin {...props} />,
    question: (props) => <IconWorldQuestion {...props} />,
    share: (props) => <IconWorldShare {...props} />,
    star: (props) => <IconWorldStar {...props} />,
    up: (props) => <IconWorldUp {...props} />,
  },
  'outline',
);
